/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;


public class App {
    public static void main (String[] args) {
        readFile();
    }


    public static void readFile() {
        try {
            Gson gson = new Gson();

            File file = new File("./resources/recentquotes.json");
            BufferedReader buffer = new BufferedReader(new FileReader(file));
            Quote[] response = gson.fromJson(buffer, Quote[].class);

//          https://www.geeksforgeeks.org/different-ways-reading-text-file-java/
            int rand = getRandom(112);
            System.out.println(response[rand].toString());

        } catch (IOException e) {
            System.out.println(e);
        }

    }
    public static int getRandom(int num){
        return (int)Math.floor(Math.random()*(num));
    }
}
